version: "2"

services:

### python3
    python3:
        image: raw34/pyspider
#        build: ./python/python3-stretch
        container_name:
            docker_python3_1
        volumes:
            - ~/.ssh:/root/.ssh
